name: PUSH
on:
  push:
    branches: [ master ]
#   pull_request:
#     branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Copy folder content recursively to remote
        uses: garygrossgarten/github-action-scp@release
        with:
          local: ./
          remote: ./git
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: multiple command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            whoami
            ls -al
            docker login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}  docker.pkg.github.com/${{ github.repository }}/test
      - name: Build container image
        uses: docker/build-push-action@v2.3.0
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.R_SECRET }}
          registry: docker.pkg.github.com
          repository: ${{ github.repository }}/test
          tag_with_sha: true
          tag_with_ref: true
